[tools]
python = "3.14"
uv = "latest"

##### Settings and environment variables #####

[settings]
python.uv_venv_auto = "create|source"

[env]
JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION = true  # silence warning about untested Node.js versions in CDK

##### Shell aliases #####

[shell_alias]
# Project-specific shortcuts
n = "mise run new"
i = "mise run install"
l = "mise run lint"
t = "mise run test"
d = "mise run deploy"
D = "mise run destroy"
c = "mise run clean"
m = "mise run"

# Common utility aliases
ll = "ls -la"
la = "ls -A"
gs = "git status"
ga = "git add"
gc = "git commit"
gp = "git push"

##### Scripts #####

[tasks.new]
description = "Create new Lambda function template"
usage = """
arg "<template>" help="Template name"
"""
run = "uv run new -n $usage_template"
alias = "n"

[tasks.rename]
description = "Rename project (run once)"
run = "uv run rename"

##### Dev setup and maintenance #####
 
[tasks.install]
description = "Install dependencies and project"
run = "uv sync"
alias = "i"

[tasks.update]
description = "Update dependencies"
run = "uv lock --upgrade"
alias = "u"

[tasks.precommit]
description = "Install pre-commit hooks"
run = "uv run pre-commit autoupdate && uv run pre-commit install"

[tasks.dev]
description = "Set up dev environment"
depends = ["precommit"]

[tasks.lint]
description = "Format and lint code"
run = """
uv run ruff format
uv run ruff check --fix
uv run ruff format
# uv run pyright
"""
alias = "l"

[tasks.test]
description = "Run tests with coverage"
run = """
uv run coverage run -m pytest .
uv run coverage report -m
uv run coverage xml
"""
alias = "t"

[tasks.clean]
description = "Clean up build artifacts and temporary files"
run = """rm -rf cdk.out .coverage .pytest_cache .ruff_cache .hypotheses"""
alias = "c"

##### Docs #####

[tasks.install-docs]
description = "Install documentation dependencies"
run = "uv sync --group docs"
hide = true

[tasks.docs]
description = "Build and deploy documentation to GitHub pages"
run = "uv run mkdocs gh-deploy --force"
depends = ["install-docs"]

[tasks.local]
description = "Serve documentation on a local server"
run = "uv run mkdocs serve"

##### Infra #####

[tasks.install-cdk]
description = "Install CDK dependencies"
run = "uv sync --group infra"
hide = true
tools = { node = "latest" }

[tasks.deploy]
description = "Deploy a CDK stack"
usage = """
arg "<stack>" help="CDK stack to deploy"
flag "-p --profile <profile>" help="AWS profile to use"
"""
run = "STACK=$usage_stack npx aws-cdk deploy ${usage_profile:+--profile $usage_profile}"
alias = "d"
depends = ["install-cdk"]

[tasks.destroy]
description = "Destroy a deployed CDK stack"
usage = """
arg "<stack>" help="CDK stack to destroy"
flag "-p --profile <profile>" help="AWS profile to use"
"""
run = "STACK=$usage_stack npx aws-cdk destroy --force ${usage_profile:+--profile $usage_profile}"
alias = "D"
depends = ["install-cdk"]
