site_name: AWS Lambda Templates - Python
repo_url: https://github.com/amrabed/aws-lambda-templates
repo_name: amrabed/aws-lambda-templates
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2026 

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow

nav:
  - Overview:
    - Overview: README.md
    - License: LICENSE.md
  - Templates:
    - Templates: template/index.md
    - Rest API: template/api.md
    - Bedrock Agent: template/agent.md
    - DynamoDB Stream: template/stream.md
    - S3 to SQS: template/s3.md
    - SQS to DynamoDB: template/sqs.md
  - Reference:
    - API: reference/api.md
    - Bedrock Agent: reference/agent.md
    - Stream: reference/stream.md
    - S3: reference/s3.md
    - SQS: reference/sqs.md
    - Repository: reference/repository.md
  - Contributing: CONTRIBUTING.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google  # Or numpy, reST, etc., based on your code style
