name: Verify code and infra

on:
  workflow_call:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install mise
        uses: jdx/mise-action@v4
      - name: Verify code and infra
        run: mise run verify
        env:
          AWS_DEFAULT_REGION: us-east-1
